/* ==========================================================================
   Diagramon · kits de decisiones (ADR)
   Un kit es una lista de decisiones ya redactadas (estado «proposed», con opciones, pros y contras, sin puntuar)
   que el consultor añade con «Añadir kit de decisiones…» en la pestaña ADR y luego puntúa con el cliente.
   Formato (ver docs/customize.md › «Decision kits»):
     { id, name: {en, es}, desc: {en, es},
       criteria: [{ id, label: {en, es}, weight }],        // criterios por defecto (peso 1..5), se copian a cada decisión sin `criteria` propio
       decisions: [{ area, title, context, criteria?,
                     options: [{ id, title, summary, pros, cons }],   // pros/cons: líneas «• …» unidas por \n
                     links?: { nodes: ['id-de-nodo'] } }] }          // ids de nodo de la plantilla; se descartan donde no existan
   Cualquier texto puede ser { en, es } o un texto simple.
   ========================================================================== */
(function () {
  const t = (en, es) => ({ en, es });
  const bl = (en, es) => ({ en: en.map(x => '• ' + x).join('\n'), es: es.map(x => '• ' + x).join('\n') });
  // opción: id, título (texto o {en, es}), [resumen en, es], [pros en[], es[]], [contras en[], es[]]
  const o = (id, title, s, p, c) => ({ id, title, summary: t(s[0], s[1]), pros: bl(p[0], p[1]), cons: bl(c[0], c[1]) });
  const d = (area, title, context, nodes, options) => ({ area: t(area[0], area[1]), title: t(title[0], title[1]), context: t(context[0], context[1]), options, links: { nodes } });

  window.DIAGRAMON_ADR_KITS = [{
    id: 'lakehouse',
    name: t('Data lakehouse · greenfield decisions', 'Data lakehouse · decisiones de un greenfield'),
    desc: t('Backlog of the decisions a new lakehouse needs, with options, pros and cons ready to score with the client.',
      'Backlog de las decisiones que necesita un lakehouse nuevo, con opciones, pros y contras listos para puntuar con el cliente.'),
    criteria: [
      { id: 'cost', label: t('Total cost', 'Costo total'), weight: 3 },
      { id: 'skills', label: t('Team skills', 'Habilidades del equipo'), weight: 4 },
      { id: 'lockin', label: t('Lock-in / portability', 'Dependencia del proveedor'), weight: 3 },
      { id: 'ops', label: t('Operability', 'Operación'), weight: 4 },
      { id: 'fit', label: t('Fit with requirements', 'Ajuste a los requisitos'), weight: 5 },
      { id: 'ttv', label: t('Time to value', 'Tiempo hasta el valor'), weight: 3 }
    ],
    decisions: [

      d(['Platform', 'Plataforma'], ['Which cloud provider hosts the lakehouse?', '¿Qué proveedor de nube aloja el lakehouse?'],
        ['The cloud choice shapes identity, networking, the available data services and the commercial terms for years. Ask the client: is there an existing enterprise agreement or committed spend, where do the source systems and the users live, which data residency or sovereignty rules apply, which cloud does the team already operate, and is a second cloud a real requirement or only a worry?',
          'La nube condiciona la identidad, la red, los servicios de datos disponibles y las condiciones comerciales durante años. Preguntar al cliente: ¿hay un acuerdo corporativo o un gasto comprometido?, ¿dónde viven los sistemas origen y los usuarios?, ¿qué reglas de residencia o soberanía de datos aplican?, ¿qué nube opera ya el equipo? y ¿una segunda nube es un requisito real o solo una preocupación?'],
        ['bronze', 'silver', 'gold', 'iam'], [
          o('A', 'Amazon Web Services', ['Broad service catalogue and the largest partner ecosystem, with object storage as the usual base of an open lakehouse.', 'Catálogo de servicios amplio y el mayor ecosistema de socios, con el almacenamiento de objetos como base habitual de un lakehouse abierto.'],
            [['Wide choice of services and regions', 'Mature object storage and IAM model', 'Large pool of engineers and partners in most markets'], ['Gran variedad de servicios y regiones', 'Almacenamiento de objetos y modelo IAM maduros', 'Gran cantidad de ingenieros y socios en la mayoría de los mercados']],
            [['Many overlapping services: a reference design is needed to avoid sprawl', 'Cost model is detailed and takes effort to forecast', 'Data services are spread over several products'], ['Muchos servicios que se solapan: hace falta un diseño de referencia para evitar dispersión', 'El modelo de costos es detallado y cuesta pronosticarlo', 'Los servicios de datos están repartidos en varios productos']]),
          o('B', 'Microsoft Azure', ['Strong fit when identity, productivity and BI already run on Microsoft services.', 'Buen encaje cuando la identidad, la ofimática y el BI ya funcionan sobre servicios de Microsoft.'],
            [['Native integration with Microsoft Entra ID and Power BI', 'Often covered by an existing enterprise agreement', 'First-party and partner lakehouse platforms available'], ['Integración nativa con Microsoft Entra ID y Power BI', 'Suele estar cubierta por un acuerdo corporativo existente', 'Hay plataformas lakehouse propias y de socios']],
            [['Product packaging and naming have changed over time: check the current roadmap', 'Some data services are tied to one cloud', 'Subscription and resource-group design needs care from day one'], ['El empaquetado y los nombres de producto han cambiado con el tiempo: revisar la hoja de ruta vigente', 'Algunos servicios de datos están atados a una sola nube', 'El diseño de suscripciones y grupos de recursos exige cuidado desde el primer día']]),
          o('C', 'Google Cloud', ['Strong analytics and ML services, with a serverless warehouse and open table support.', 'Servicios de analítica y ML sólidos, con un almacén sin servidor y soporte de tablas abiertas.'],
            [['Serverless analytics with little infrastructure to manage', 'Simple project and IAM hierarchy', 'Good fit for analytics and ML-heavy workloads'], ['Analítica sin servidor con poca infraestructura que gestionar', 'Jerarquía sencilla de proyectos e IAM', 'Buen encaje con cargas intensivas en analítica y ML']],
            [['Smaller local presence and partner pool in some markets', 'Fewer certified engineers on the market in many regions', 'Integration with a Microsoft-centred identity setup needs extra work'], ['Menor presencia local y menos socios en algunos mercados', 'Menos ingenieros certificados disponibles en muchas regiones', 'Integrarse con una identidad centrada en Microsoft requiere trabajo extra']]),
          o('D', t('Multi-cloud or regional provider', 'Multinube o proveedor regional'), ['Spread the platform over more than one provider, or use a regional or sovereign cloud for part of it.', 'Repartir la plataforma entre más de un proveedor, o usar una nube regional o soberana para una parte.'],
            [['Reduces dependence on a single vendor', 'Can satisfy strict residency or sovereignty rules', 'Lets each workload use the best-fitting service'], ['Reduce la dependencia de un único proveedor', 'Puede cumplir reglas estrictas de residencia o soberanía', 'Cada carga puede usar el servicio que mejor le encaja']],
            [['Higher complexity and duplicated skills and tooling', 'Cross-cloud data transfer adds cost and latency', 'Often ends up at the lowest common denominator of features'], ['Mayor complejidad y duplicación de habilidades y herramientas', 'La transferencia de datos entre nubes suma costo y latencia', 'Suele terminar en el mínimo común de funciones']])
        ]),

      d(['Platform', 'Plataforma'], ['Which lakehouse platform?', '¿Qué plataforma lakehouse?'],
        ['This is the main engine and the main commercial relationship of the programme. Ask the client: SQL-first analysts or code-first engineers, how much machine learning is planned, how much control over storage and compute they want, which BI tools are in place, and whether the team prefers a managed service or building from components.',
          'Es el motor principal y la relación comercial más importante del programa. Preguntar al cliente: ¿analistas centrados en SQL o ingenieros centrados en código?, ¿cuánto machine learning se planea?, ¿cuánto control quieren sobre el almacenamiento y el cómputo?, ¿qué herramientas de BI usan? y ¿prefiere el equipo un servicio gestionado o construir a partir de componentes?'],
        ['transf', 'sqlwh', 'bronze'], [
          o('A', 'Databricks', ['Spark-based lakehouse platform covering data engineering, SQL and ML, available on the major clouds.', 'Plataforma lakehouse basada en Spark que cubre ingeniería de datos, SQL y ML, disponible en las nubes principales.'],
            [['Strong for data engineering and ML in the same place', 'Runs on the three major clouds with similar concepts', 'Built around open formats and open-source engines'], ['Muy sólida para ingeniería de datos y ML en un mismo lugar', 'Funciona en las tres nubes principales con conceptos similares', 'Construida sobre formatos abiertos y motores de código abierto']],
            [['Consumption-based pricing needs tuning and guardrails', 'Platform and cloud account both have to be operated', 'SQL-only teams face a steeper start than with a pure warehouse'], ['El precio por consumo requiere ajuste y límites', 'Hay que operar tanto la plataforma como la cuenta cloud', 'Los equipos solo SQL tienen un arranque más cuesta arriba que con un almacén puro']]),
          o('B', 'Snowflake', ['SQL-first managed data platform with separate storage and compute and built-in governance.', 'Plataforma de datos gestionada, centrada en SQL, con almacenamiento y cómputo separados y gobierno integrado.'],
            [['Low operational effort and quick start for SQL teams', 'Strong sharing and governance features', 'Works on the major clouds'], ['Poco esfuerzo operativo y arranque rápido para equipos SQL', 'Funciones sólidas de compartición y gobierno', 'Funciona en las nubes principales']],
            [['Compute is credit-based: needs cost controls and monitoring', 'Spark-style engineering and ML use a different programming model', 'Data lives in platform-managed storage unless open tables are used on purpose'], ['El cómputo se paga por créditos: requiere controles y monitoreo de costos', 'La ingeniería estilo Spark y el ML usan otro modelo de programación', 'Los datos viven en almacenamiento gestionado por la plataforma salvo que se usen tablas abiertas a propósito']]),
          o('C', 'Microsoft Fabric', ['SaaS analytics platform on Microsoft with a shared OneLake storage layer and Power BI built in.', 'Plataforma analítica SaaS de Microsoft con una capa de almacenamiento compartida (OneLake) y Power BI integrado.'],
            [['One product for ingestion, engineering, warehouse and BI', 'Delta tables in a shared lake by default', 'Natural fit for Microsoft-centred organisations'], ['Un solo producto para ingesta, ingeniería, almacén y BI', 'Tablas Delta en un lago compartido por defecto', 'Encaje natural para organizaciones centradas en Microsoft']],
            [['Runs only on Microsoft cloud', 'Capacity-based sizing needs planning and monitoring', 'Younger service that evolves quickly: check feature maturity for each need'], ['Funciona solo en la nube de Microsoft', 'El dimensionamiento por capacidad requiere planificación y monitoreo', 'Servicio más joven y en rápida evolución: comprobar la madurez de cada función necesaria']]),
          o('D', t('Cloud-native services (assembled)', 'Servicios nativos de la nube (ensamblados)'), ['Build the lakehouse from object storage, open-source engines and the cloud\'s own services.', 'Construir el lakehouse con almacenamiento de objetos, motores de código abierto y los servicios propios de la nube.'],
            [['Maximum flexibility and open components', 'Pay only for the building blocks used', 'Easier to swap one component later'], ['Máxima flexibilidad y componentes abiertos', 'Se paga solo por los bloques que se usan', 'Es más fácil reemplazar un componente más adelante']],
            [['Integration and upgrades fall on your team', 'Governance and security are stitched together from several tools', 'Slowest route to the first useful result'], ['La integración y las actualizaciones recaen en tu equipo', 'El gobierno y la seguridad se arman con varias herramientas', 'Es el camino más lento hasta el primer resultado útil']])
        ]),

      d(['Storage', 'Almacenamiento'], ['Which open table format?', '¿Qué formato de tabla abierto?'],
        ['The table format decides which engines can read and write the data, how updates and deletes work and how easy it is to change platform later. Ask the client: which engines and tools must read the same tables, whether data must be shared with partners on other platforms, how often rows are updated, and how much portability matters compared with convenience.',
          'El formato de tabla decide qué motores pueden leer y escribir los datos, cómo funcionan las actualizaciones y borrados, y qué tan fácil será cambiar de plataforma más adelante. Preguntar al cliente: ¿qué motores y herramientas deben leer las mismas tablas?, ¿se comparten datos con socios en otras plataformas?, ¿con qué frecuencia se actualizan filas? y ¿cuánto importa la portabilidad frente a la comodidad?'],
        ['bronze', 'silver', 'gold'], [
          o('A', 'Delta Lake', ['Open table format with ACID transactions, time travel and a mature Spark implementation.', 'Formato de tabla abierto con transacciones ACID, viaje en el tiempo y una implementación madura en Spark.'],
            [['Mature and widely used, especially with Spark and Databricks', 'Default format in Microsoft Fabric', 'Good tooling for streaming and batch on the same table'], ['Maduro y muy usado, sobre todo con Spark y Databricks', 'Formato por defecto en Microsoft Fabric', 'Buenas herramientas para streaming y batch sobre la misma tabla']],
            [['Support outside the Spark ecosystem varies by engine and feature', 'Some advanced features depend on the platform you run it on', 'Reading from Iceberg-only tools may need a compatibility layer'], ['El soporte fuera del ecosistema Spark varía según motor y función', 'Algunas funciones avanzadas dependen de la plataforma donde se ejecuta', 'Leer desde herramientas solo Iceberg puede requerir una capa de compatibilidad']]),
          o('B', 'Apache Iceberg', ['Open table format designed for many engines, with a catalog specification and partition evolution.', 'Formato de tabla abierto pensado para muchos motores, con una especificación de catálogo y evolución de particiones.'],
            [['Broad multi-engine support (Spark, Trino, Flink and several warehouses)', 'Partition evolution and hidden partitioning', 'Open catalog specification helps portability'], ['Amplio soporte multimotor (Spark, Trino, Flink y varios almacenes)', 'Evolución de particiones y particionado oculto', 'La especificación abierta de catálogo ayuda a la portabilidad']],
            [['Needs a deliberate catalog choice', 'Maintenance (compaction, snapshot expiry) is yours unless a service does it', 'Write feature parity differs between engines'], ['Exige elegir el catálogo con criterio', 'El mantenimiento (compactación, expiración de snapshots) es tuyo salvo que un servicio lo haga', 'Las funciones de escritura no son idénticas entre motores']]),
          o('C', 'Apache Hudi', ['Table format built around record-level upserts and incremental processing.', 'Formato de tabla construido en torno a upserts por registro y procesamiento incremental.'],
            [['Designed for frequent upserts and deletes', 'Incremental reads suit CDC-style pipelines', 'Fine-grained control over table services'], ['Pensado para upserts y borrados frecuentes', 'Las lecturas incrementales encajan con pipelines tipo CDC', 'Control fino de los servicios de la tabla']],
            [['Smaller ecosystem and community than the other two', 'Fewer engines and managed services support it', 'More tuning knobs mean more to learn'], ['Ecosistema y comunidad más pequeños que los otros dos', 'Lo soportan menos motores y servicios gestionados', 'Más parámetros de ajuste implican más que aprender']]),
          o('D', t('Platform-managed tables (no open format)', 'Tablas gestionadas por la plataforma (sin formato abierto)'), ['Use the proprietary table storage of the chosen platform.', 'Usar el almacenamiento de tablas propio de la plataforma elegida.'],
            [['Simplest to start and best tuned by the vendor', 'No format maintenance to plan', 'Fewer moving parts for the team'], ['Lo más sencillo para empezar y mejor optimizado por el proveedor', 'No hay mantenimiento de formato que planificar', 'Menos piezas móviles para el equipo']],
            [['Highest lock-in: leaving means exporting and rebuilding', 'Other engines cannot read the data directly', 'Harder to share data with partners on other platforms'], ['Mayor dependencia: salir implica exportar y reconstruir', 'Otros motores no pueden leer los datos directamente', 'Más difícil compartir datos con socios en otras plataformas']])
        ]),

      d(['Storage', 'Almacenamiento'], ['How is storage organised? Layers and layout', '¿Cómo se organiza el almacenamiento? Capas y estructura'],
        ['The layer model sets where raw data is kept, where it is cleaned and where business models live, and drives naming, retention and access rules. Ask the client: must raw data be kept unchanged for audit, how long is history kept, where does personal data live and who may see it, and which teams will own which datasets.',
          'El modelo de capas define dónde se guarda el dato crudo, dónde se limpia y dónde viven los modelos de negocio, y condiciona nombres, retención y reglas de acceso. Preguntar al cliente: ¿hay que conservar el dato crudo sin cambios para auditoría?, ¿cuánto tiempo se guarda el historial?, ¿dónde vive el dato personal y quién puede verlo? y ¿qué equipos serán dueños de qué conjuntos de datos?'],
        ['bronze', 'silver', 'gold'], [
          o('A', t('Three layers: bronze, silver, gold', 'Tres capas: bronce, plata, oro'), ['Raw copy, cleaned and conformed data, and business-ready models in separate layers.', 'Copia cruda, datos limpios y conformados, y modelos listos para el negocio en capas separadas.'],
            [['Widely understood pattern with clear contracts between layers', 'Reprocessing from raw is always possible', 'Access rules can differ per layer'], ['Patrón muy conocido, con contratos claros entre capas', 'Siempre se puede reprocesar desde el dato crudo', 'Las reglas de acceso pueden ser distintas en cada capa']],
            [['More copies of the data and more storage', 'Layers without written rules turn into dumping grounds', 'More pipelines to build and monitor'], ['Más copias del dato y más almacenamiento', 'Sin reglas escritas, las capas se vuelven un cajón de sastre', 'Más pipelines que construir y vigilar']]),
          o('B', t('Two zones: raw and curated', 'Dos zonas: cruda y curada'), ['Keep an immutable raw zone and one curated zone for everything consumers use.', 'Mantener una zona cruda inmutable y una zona curada para todo lo que usan los consumidores.'],
            [['Fewer hops, lower cost and latency', 'Simpler to explain and operate', 'Good for small teams and few sources'], ['Menos saltos, menor costo y latencia', 'Más simple de explicar y operar', 'Adecuado para equipos pequeños y pocas fuentes']],
            [['Cleansing and business logic mix in one place', 'Harder to reuse cleaned data across products', 'May need to be split later as the platform grows'], ['La limpieza y la lógica de negocio se mezclan en un solo lugar', 'Es más difícil reutilizar el dato limpio entre productos', 'Puede que haya que dividirla más adelante cuando la plataforma crezca']]),
          o('C', t('Medallion organised by domain', 'Medallón organizado por dominio'), ['Each business domain has its own set of layers and catalog, under shared standards.', 'Cada dominio de negocio tiene su propio conjunto de capas y catálogo, bajo estándares compartidos.'],
            [['Ownership matches the organisation', 'Cost and access are easier to attribute', 'Domains can move at their own pace'], ['La propiedad refleja la organización', 'Es más fácil atribuir costos y accesos', 'Cada dominio puede avanzar a su ritmo']],
            [['Needs strong shared standards and governance', 'Risk of duplicated pipelines and datasets', 'Cross-domain models need clear rules'], ['Exige estándares y gobierno compartidos sólidos', 'Riesgo de pipelines y datasets duplicados', 'Los modelos entre dominios necesitan reglas claras']]),
          o('D', t('Medallion with a modelled core (e.g. Data Vault)', 'Medallón con un núcleo modelado (p. ej. Data Vault)'), ['Add a modelled integration layer between cleansed data and the business models.', 'Añadir una capa de integración modelada entre el dato limpio y los modelos de negocio.'],
            [['Strong history and auditability', 'Integrates many sources in a stable way', 'Absorbs source changes with limited rework'], ['Historial y trazabilidad sólidos', 'Integra muchas fuentes de forma estable', 'Absorbe cambios de las fuentes con poco retrabajo']],
            [['Needs modelling skills and upfront effort', 'More joins for consumers, usually hidden behind a gold layer', 'Slower to the first business result'], ['Requiere habilidades de modelado y esfuerzo inicial', 'Más joins para los consumidores, normalmente ocultos tras una capa oro', 'Tarda más en dar el primer resultado de negocio']])
        ]),

      d(['Governance', 'Gobierno'], ['Which catalog and governance approach?', '¿Qué enfoque de catálogo y gobierno?'],
        ['The catalog is where permissions, lineage, descriptions and table discovery come together. Ask the client: is there already a data catalog or governance tool, who defines owners and stewards, which regulations demand lineage or classification, and how many engines need to share the same permissions.',
          'El catálogo es donde se reúnen permisos, linaje, descripciones y descubrimiento de tablas. Preguntar al cliente: ¿ya existe un catálogo o una herramienta de gobierno?, ¿quién define dueños y responsables de datos?, ¿qué normativas exigen linaje o clasificación? y ¿cuántos motores deben compartir los mismos permisos?'],
        ['catalog'], [
          o('A', t('Catalog built into the chosen platform', 'Catálogo integrado en la plataforma elegida'), ['Use the platform\'s own catalog for permissions, lineage and discovery.', 'Usar el catálogo propio de la plataforma para permisos, linaje y descubrimiento.'],
            [['Works out of the box with the platform\'s engines', 'One place for access control and audit', 'Lowest effort to start'], ['Funciona desde el primer día con los motores de la plataforma', 'Un solo lugar para el control de acceso y la auditoría', 'Es lo que menos esfuerzo requiere para empezar']],
            [['Tied to that platform: other engines may see only part of it', 'Exporting metadata later takes work', 'Features follow the vendor roadmap'], ['Atado a esa plataforma: otros motores pueden ver solo una parte', 'Exportar los metadatos más adelante da trabajo', 'Las funciones siguen la hoja de ruta del proveedor']]),
          o('B', t('Open catalog (REST-based, standards-led)', 'Catálogo abierto (basado en REST y estándares)'), ['Run an open catalog that several engines can use, such as an implementation of the Iceberg REST specification.', 'Operar un catálogo abierto que usen varios motores, como una implementación de la especificación REST de Iceberg.'],
            [['Several engines share one view of the tables', 'Easier to change platform later', 'Open-source options are available'], ['Varios motores comparten una misma vista de las tablas', 'Es más fácil cambiar de plataforma después', 'Hay opciones de código abierto']],
            [['One more service to run, secure and upgrade', 'Fine-grained policies are usually less complete than in native catalogs', 'Needs a clear owner on the platform team'], ['Un servicio más que operar, asegurar y actualizar', 'Las políticas finas suelen ser menos completas que en los catálogos nativos', 'Necesita un responsable claro en el equipo de plataforma']]),
          o('C', t('Enterprise catalog tool on top', 'Herramienta de catálogo corporativa encima'), ['Add a dedicated catalog and governance tool for glossary, stewardship workflows and cross-system lineage; it complements A or B.', 'Añadir una herramienta dedicada de catálogo y gobierno para glosario, flujos de responsables y linaje entre sistemas; complementa a A o B.'],
            [['Covers the whole estate, not only the lakehouse', 'Business glossary and stewardship workflows', 'Useful when governance is run by a separate team'], ['Cubre todo el ecosistema, no solo el lakehouse', 'Glosario de negocio y flujos de responsables de datos', 'Útil cuando el gobierno lo lleva un equipo aparte']],
            [['Extra licence and integration effort', 'Metadata can drift if not synchronised', 'Value depends on adoption by stewards'], ['Licencia extra y esfuerzo de integración', 'Los metadatos pueden desalinearse si no se sincronizan', 'El valor depende de que los responsables lo adopten']])
        ]),

      d(['Ingestion', 'Ingesta'], ['How is batch data ingested?', '¿Cómo se ingieren los datos por lotes?'],
        ['Most sources (ERP, CRM, files, SaaS applications) will arrive in batches. Ask the client: how many sources and of what type, how fresh the data must be, whether APIs and export files are stable, what happens when a source changes its schema, and whether the team prefers buying connectors or writing them.',
          'La mayoría de las fuentes (ERP, CRM, archivos, aplicaciones SaaS) llegará por lotes. Preguntar al cliente: ¿cuántas fuentes y de qué tipo?, ¿qué tan fresco debe estar el dato?, ¿son estables las APIs y los archivos de exportación?, ¿qué pasa cuando una fuente cambia su esquema? y ¿prefiere el equipo comprar conectores o escribirlos?'],
        ['ingb', 'files', 'erp'], [
          o('A', t('Managed ELT connectors (SaaS)', 'Conectores ELT gestionados (SaaS)'), ['Buy a service with ready-made connectors that load sources into the lake.', 'Contratar un servicio con conectores listos que cargan las fuentes en el lago.'],
            [['Fastest way to cover common sources', 'Vendor maintains connectors and schema handling', 'Little code to own'], ['La forma más rápida de cubrir fuentes comunes', 'El proveedor mantiene los conectores y el manejo de esquemas', 'Poco código propio que mantener']],
            [['Cost grows with data volume', 'Less control over load logic', 'Uncommon sources may not be covered'], ['El costo crece con el volumen de datos', 'Menos control sobre la lógica de carga', 'Las fuentes poco comunes pueden no estar cubiertas']]),
          o('B', t('Native ingestion of the chosen platform or cloud', 'Ingesta nativa de la plataforma o nube elegida'), ['Use the loading and pipeline tools that come with the platform or the cloud.', 'Usar las herramientas de carga y pipelines que vienen con la plataforma o la nube.'],
            [['Integrated with security, monitoring and billing', 'No extra vendor to contract', 'Good fit for files landing in object storage'], ['Integrada con seguridad, monitoreo y facturación', 'No hay otro proveedor que contratar', 'Buen encaje para archivos que llegan al almacenamiento de objetos']],
            [['Connector coverage differs between platforms', 'Skills do not carry over if the platform changes', 'Some sources still need custom code'], ['La cobertura de conectores varía entre plataformas', 'Las habilidades no se trasladan si cambia la plataforma', 'Algunas fuentes siguen necesitando código propio']]),
          o('C', t('Open-source ingestion framework', 'Framework de ingesta de código abierto'), ['Run an open-source connector framework or library on your own infrastructure.', 'Operar un framework o librería de conectores de código abierto en tu propia infraestructura.'],
            [['No per-volume licence fees', 'Can be extended with your own connectors', 'Portable across clouds'], ['Sin licencias por volumen', 'Se puede extender con conectores propios', 'Portable entre nubes']],
            [['You run, patch and monitor it', 'Connector quality varies', 'Support depends on the community or a paid plan'], ['Tú lo operas, actualizas y monitoreas', 'La calidad de los conectores varía', 'El soporte depende de la comunidad o de un plan de pago']]),
          o('D', t('Custom code (Python / Spark jobs)', 'Código propio (jobs en Python / Spark)'), ['Write ingestion jobs for each source and run them in the orchestrator.', 'Escribir jobs de ingesta para cada fuente y ejecutarlos en el orquestador.'],
            [['Full control and any source can be covered', 'No extra licences', 'Fits unusual protocols and formats'], ['Control total y se puede cubrir cualquier fuente', 'Sin licencias adicionales', 'Sirve para protocolos y formatos poco comunes']],
            [['Highest build and maintenance effort', 'Every source needs its own error and schema handling', 'Knowledge concentrates in a few people'], ['Es el mayor esfuerzo de construcción y mantenimiento', 'Cada fuente necesita su propio manejo de errores y esquemas', 'El conocimiento se concentra en pocas personas']])
        ]),

      d(['Ingestion', 'Ingesta'], ['How are changes captured from operational databases (CDC)?', '¿Cómo se capturan los cambios de las bases operacionales (CDC)?'],
        ['Change data capture keeps the lakehouse close to the operational systems without heavy full extracts, but it touches production databases. Ask the client: which database engines and versions, whether the DBA allows reading transaction logs, how deletes and schema changes must appear in the lake, the expected latency and the data volume per day.',
          'La captura de cambios (CDC) mantiene el lakehouse cerca de los sistemas operacionales sin extracciones completas pesadas, pero toca las bases de producción. Preguntar al cliente: ¿qué motores de base de datos y versiones?, ¿el DBA permite leer los logs de transacciones?, ¿cómo deben verse los borrados y cambios de esquema en el lago?, ¿qué latencia se espera? y ¿cuál es el volumen diario?'],
        ['ingc', 'opdb'], [
          o('A', t('Log-based CDC with open-source tooling (e.g. Debezium)', 'CDC por log con herramientas de código abierto (p. ej. Debezium)'), ['Read the database transaction logs and publish changes as events.', 'Leer los logs de transacciones de la base y publicar los cambios como eventos.'],
            [['Low impact on the source and captures deletes', 'Open and portable, large community', 'Row-level changes with ordering'], ['Bajo impacto en el origen y captura los borrados', 'Abierto y portable, con una comunidad grande', 'Cambios por fila con orden']],
            [['Usually needs a message broker and its operation', 'Support for each database varies in detail', 'Schema changes need a clear process'], ['Normalmente requiere un broker de mensajes y su operación', 'El soporte de cada base varía en los detalles', 'Los cambios de esquema necesitan un proceso claro']]),
          o('B', t('Managed CDC / replication service', 'Servicio gestionado de CDC / replicación'), ['Use the cloud provider\'s or a vendor\'s replication service to land changes in the lake.', 'Usar el servicio de replicación del proveedor cloud o de un fabricante para depositar los cambios en el lago.'],
            [['Quicker to set up and operated by the vendor', 'Support for many database engines', 'Includes monitoring of lag and errors'], ['Más rápido de configurar y operado por el proveedor', 'Soporte para muchos motores de base de datos', 'Incluye monitoreo del retraso y los errores']],
            [['Licence or consumption cost grows with volume', 'Less flexibility in transformation and formats', 'Dependence on the service\'s supported versions'], ['El costo de licencia o consumo crece con el volumen', 'Menos flexibilidad en transformación y formatos', 'Dependencia de las versiones que el servicio soporte']]),
          o('C', t('Incremental extraction (timestamp or key)', 'Extracción incremental (marca de tiempo o clave)'), ['Query only the rows changed since the last run, using an update column.', 'Consultar solo las filas modificadas desde la última ejecución, usando una columna de actualización.'],
            [['Simple and needs no access to logs', 'Works with almost any database', 'Easy to explain and test'], ['Simple y no necesita acceso a los logs', 'Funciona con casi cualquier base de datos', 'Fácil de explicar y probar']],
            [['Misses hard deletes unless handled separately', 'Needs a reliable update column on every table', 'Adds query load on the source'], ['No detecta borrados físicos si no se tratan aparte', 'Necesita una columna de actualización fiable en cada tabla', 'Añade carga de consultas en el origen']]),
          o('D', t('Periodic full snapshots', 'Copias completas periódicas'), ['Reload full tables on a schedule and compare in the lake.', 'Recargar las tablas completas con un horario y comparar en el lago.'],
            [['Simplest approach and easy to recover', 'No special database permissions', 'Good enough for small reference tables'], ['El enfoque más simple y fácil de recuperar', 'No exige permisos especiales en la base', 'Suficiente para tablas de referencia pequeñas']],
            [['Heavy on the source and the network for large tables', 'Longer latency between runs', 'Cost grows quickly with data size'], ['Pesado para el origen y la red con tablas grandes', 'Mayor latencia entre ejecuciones', 'El costo crece rápido con el tamaño de los datos']])
        ]),

      d(['Ingestion', 'Ingesta'], ['What streaming capability is needed, and when?', '¿Qué capacidad de streaming se necesita y cuándo?'],
        ['Streaming adds cost, skills and operational duties, so it should be driven by use cases rather than fashion. Ask the client: which decisions truly need data within seconds or minutes, what happens if it arrives an hour late, who will be on call for the pipelines, and whether hourly micro-batches are enough for phase 1.',
          'El streaming añade costo, habilidades y obligaciones operativas, así que debe responder a casos de uso y no a modas. Preguntar al cliente: ¿qué decisiones necesitan realmente el dato en segundos o minutos?, ¿qué ocurre si llega con una hora de retraso?, ¿quién estará de guardia para los pipelines? y ¿bastan microlotes cada hora en la fase 1?'],
        ['ings', 'evt'], [
          o('A', t('Not in phase 1 (batch and micro-batch)', 'No en la fase 1 (batch y microlotes)'), ['Start with frequent batches and design the layers so streaming can be added later.', 'Empezar con lotes frecuentes y diseñar las capas para poder añadir streaming después.'],
            [['Lowest cost and complexity', 'Team can focus on data quality and models first', 'Decision can be revisited with real use cases'], ['Menor costo y complejidad', 'El equipo se concentra primero en calidad y modelos', 'La decisión se puede revisar con casos de uso reales']],
            [['A real-time use case found later may force a redesign', 'Stakeholders may expect faster data than delivered', 'Needs a clear note of the latency promised'], ['Un caso de uso en tiempo real descubierto después puede forzar un rediseño', 'Los interesados pueden esperar datos más rápidos de lo entregado', 'Hay que dejar claro por escrito la latencia prometida']]),
          o('B', t('Cloud-provider streaming service', 'Servicio de streaming del proveedor cloud'), ['Use the managed event streaming service of the chosen cloud.', 'Usar el servicio gestionado de streaming de eventos de la nube elegida.'],
            [['Managed, integrated with the cloud\'s security and monitoring', 'Scales without managing brokers', 'Quick to start'], ['Gestionado e integrado con la seguridad y el monitoreo de la nube', 'Escala sin gestionar brokers', 'Rápido de poner en marcha']],
            [['APIs and limits differ per cloud', 'Moving to another cloud means rework', 'Cost depends on throughput and retention'], ['Las APIs y los límites cambian según la nube', 'Cambiar de nube implica retrabajo', 'El costo depende del caudal y la retención']]),
          o('C', t('Apache Kafka (managed or self-run)', 'Apache Kafka (gestionado o propio)'), ['Use Kafka as the event backbone, from a managed service or run by the team.', 'Usar Kafka como columna vertebral de eventos, desde un servicio gestionado o operado por el equipo.'],
            [['De-facto standard with a large ecosystem', 'Portable across clouds and on-premises', 'Rich connectors and stream processing options'], ['Estándar de facto con un gran ecosistema', 'Portable entre nubes y on-premise', 'Muchos conectores y opciones de procesamiento de flujos']],
            [['Operationally demanding if self-run', 'Skills are specialised', 'Managed offerings add their own cost'], ['Exigente de operar si lo gestiona el equipo', 'Las habilidades son especializadas', 'Las ofertas gestionadas añaden su propio costo']]),
          o('D', t('Streaming inside the lakehouse platform', 'Streaming dentro de la plataforma lakehouse'), ['Ingest events directly into tables with the platform\'s streaming features.', 'Ingerir eventos directamente en tablas con las funciones de streaming de la plataforma.'],
            [['Same tools and tables as batch', 'Fewer components to run', 'Good for analytics-grade latency (seconds to minutes)'], ['Mismas herramientas y tablas que el batch', 'Menos componentes que operar', 'Adecuado para latencias analíticas (segundos a minutos)']],
            [['Not a replacement for an operational event bus', 'Tied to the platform\'s behaviour and pricing', 'Needs a source that can publish events'], ['No sustituye a un bus de eventos operacional', 'Atado al comportamiento y precio de la plataforma', 'Necesita una fuente que pueda publicar eventos']])
        ]),

      d(['Processing', 'Procesamiento'], ['Which transformation approach?', '¿Qué enfoque de transformación?'],
        ['Transformations hold the business rules and most of the long-term maintenance effort. Ask the client: are the builders mostly SQL analysts or software engineers, how big are the largest datasets, how will tests and code reviews work, and whether non-SQL logic (parsing, ML features) is expected.',
          'Las transformaciones concentran las reglas de negocio y la mayor parte del esfuerzo de mantenimiento a largo plazo. Preguntar al cliente: ¿quienes construyen son sobre todo analistas SQL o ingenieros de software?, ¿qué tan grandes son los datasets mayores?, ¿cómo serán las pruebas y las revisiones de código? y ¿se espera lógica que no sea SQL (parsing, features de ML)?'],
        ['transf'], [
          o('A', 'dbt', ['SQL models in version control, with tests and documentation, run on the warehouse or lakehouse engine.', 'Modelos SQL en control de versiones, con pruebas y documentación, ejecutados en el motor del almacén o lakehouse.'],
            [['Familiar to SQL analysts and good engineering habits', 'Tests, docs and lineage come with the project', 'Large community and portable across engines'], ['Familiar para analistas SQL y fomenta buenas prácticas de ingeniería', 'Pruebas, documentación y linaje vienen con el proyecto', 'Comunidad grande y portable entre motores']],
            [['Mostly SQL: non-SQL logic needs another tool', 'Another tool and (optionally) a service to run', 'Batch oriented'], ['Principalmente SQL: la lógica que no es SQL necesita otra herramienta', 'Una herramienta más y, opcionalmente, un servicio para ejecutarla', 'Orientado a batch']]),
          o('B', t('Spark jobs and notebooks (PySpark / Scala)', 'Jobs y notebooks de Spark (PySpark / Scala)'), ['Write transformations as code on a distributed engine.', 'Escribir las transformaciones como código en un motor distribuido.'],
            [['Handles very large data and complex logic', 'Full programming language, libraries and tests', 'Same code for batch and streaming'], ['Maneja datos muy grandes y lógica compleja', 'Lenguaje de programación completo, con librerías y pruebas', 'El mismo código sirve para batch y streaming']],
            [['Needs engineering skills and discipline', 'Notebook code without standards becomes hard to maintain', 'Cluster tuning affects cost'], ['Requiere habilidades y disciplina de ingeniería', 'El código en notebooks sin estándares se vuelve difícil de mantener', 'El ajuste del clúster afecta el costo']]),
          o('C', t('Platform declarative pipelines', 'Pipelines declarativos de la plataforma'), ['Declare the tables and rules; the platform handles dependencies, retries and incremental updates.', 'Declarar las tablas y reglas; la plataforma gestiona dependencias, reintentos y actualizaciones incrementales.'],
            [['Less plumbing code to write and maintain', 'Built-in quality rules and monitoring', 'Batch and streaming in one model'], ['Menos código de infraestructura que escribir y mantener', 'Reglas de calidad y monitoreo integrados', 'Batch y streaming en un mismo modelo']],
            [['Specific to one platform: code is not portable', 'Features and limits follow the vendor', 'Less control over execution details'], ['Específico de una plataforma: el código no es portable', 'Las funciones y límites siguen al proveedor', 'Menos control sobre los detalles de ejecución']])
        ]),

      d(['Processing', 'Procesamiento'], ['Which orchestration tool?', '¿Qué herramienta de orquestación?'],
        ['The orchestrator runs, retries and monitors every pipeline, so it quickly becomes a critical component. Ask the client: how many pipelines and dependencies across systems are expected, who writes and who monitors them, which alerting channel is used, and whether jobs outside the lakehouse (ERP, files, APIs) must be coordinated too.',
          'El orquestador ejecuta, reintenta y monitorea todos los pipelines, así que pronto se vuelve un componente crítico. Preguntar al cliente: ¿cuántos pipelines y dependencias entre sistemas se esperan?, ¿quién los escribe y quién los monitorea?, ¿qué canal de alertas se usa? y ¿hay que coordinar también tareas fuera del lakehouse (ERP, archivos, APIs)?'],
        ['orch'], [
          o('A', t('Platform-native workflows', 'Workflows nativos de la plataforma'), ['Schedule and chain jobs with the orchestration built into the chosen platform.', 'Programar y encadenar jobs con la orquestación integrada en la plataforma elegida.'],
            [['Nothing extra to install or run', 'Integrated with the platform\'s monitoring and permissions', 'Fast to start'], ['No hay nada extra que instalar ni operar', 'Integrada con el monitoreo y los permisos de la plataforma', 'Rápida para empezar']],
            [['Weaker for work outside that platform', 'Definitions are not portable', 'Advanced scheduling can be limited'], ['Más débil para trabajos fuera de esa plataforma', 'Las definiciones no son portables', 'La programación avanzada puede ser limitada']]),
          o('B', 'Apache Airflow', ['Established open-source orchestrator with workflows defined in Python, available as managed or self-run.', 'Orquestador de código abierto consolidado, con workflows definidos en Python, disponible gestionado o propio.'],
            [['Very large ecosystem of integrations', 'Orchestrates across any system', 'Widely known by engineers'], ['Ecosistema muy grande de integraciones', 'Orquesta entre cualquier sistema', 'Muy conocido entre los ingenieros']],
            [['Operating it yourself takes effort; managed services cost extra', 'Dependency and upgrade management', 'Task-centric model, less aware of the data produced'], ['Operarlo uno mismo da trabajo; los servicios gestionados cuestan extra', 'Gestión de dependencias y actualizaciones', 'Modelo centrado en tareas, menos consciente de los datos producidos']]),
          o('C', t('Asset-oriented orchestrator (e.g. Dagster, Prefect)', 'Orquestador orientado a activos (p. ej. Dagster, Prefect)'), ['Define pipelines around the data assets they produce, with built-in testing and observability.', 'Definir los pipelines alrededor de los activos de datos que producen, con pruebas y observabilidad integradas.'],
            [['Good developer experience and local testing', 'Lineage of assets is natural', 'Open-source core with managed options'], ['Buena experiencia para desarrolladores y pruebas locales', 'El linaje de los activos es natural', 'Núcleo de código abierto con opciones gestionadas']],
            [['Smaller community and talent pool than Airflow', 'Another platform to learn and run', 'Fewer ready-made integrations'], ['Comunidad y talento disponible más reducidos que Airflow', 'Otra plataforma que aprender y operar', 'Menos integraciones ya hechas']]),
          o('D', t('Cloud provider workflow service', 'Servicio de workflows del proveedor cloud'), ['Use the workflow or data-pipeline service of the chosen cloud.', 'Usar el servicio de workflows o pipelines de datos de la nube elegida.'],
            [['Managed and integrated with the cloud\'s identity and monitoring', 'Pay per use', 'Good coverage of the cloud\'s own services'], ['Gestionado e integrado con la identidad y el monitoreo de la nube', 'Se paga por uso', 'Buena cobertura de los servicios de esa nube']],
            [['Tied to one cloud', 'Complex logic can be awkward to express', 'Skills do not transfer between clouds'], ['Atado a una sola nube', 'La lógica compleja puede ser incómoda de expresar', 'Las habilidades no se transfieren entre nubes']])
        ]),

      d(['Governance', 'Gobierno'], ['How are data quality and observability handled?', '¿Cómo se gestionan la calidad y la observabilidad de los datos?'],
        ['Without agreed quality checks, users lose trust in the platform quickly. Ask the client: which datasets are critical and what "wrong" means for each, who fixes an issue and how fast, whether data contracts exist with source teams, and where alerts should go.',
          'Sin controles de calidad acordados, los usuarios pierden la confianza en la plataforma rápidamente. Preguntar al cliente: ¿qué datasets son críticos y qué significa «incorrecto» en cada uno?, ¿quién corrige un problema y en cuánto tiempo?, ¿existen contratos de datos con los equipos de las fuentes? y ¿adónde deben llegar las alertas?'],
        ['dq', 'obs'], [
          o('A', t('Tests inside the transformation code', 'Pruebas dentro del código de transformación'), ['Use the tests and expectations of the transformation tool (uniqueness, not null, accepted values, freshness).', 'Usar las pruebas y expectativas de la herramienta de transformación (unicidad, no nulos, valores aceptados, frescura).'],
            [['Lowest effort and checks live next to the logic', 'Runs in the existing pipelines', 'Version-controlled and reviewed with the code'], ['Mínimo esfuerzo y los controles viven junto a la lógica', 'Se ejecuta en los pipelines existentes', 'Con control de versiones y revisión junto al código']],
            [['Limited statistical and anomaly detection', 'Does not cover data before it enters the pipeline', 'Alerting and ownership still need to be designed'], ['Detección estadística y de anomalías limitada', 'No cubre el dato antes de entrar al pipeline', 'Las alertas y la responsabilidad siguen por diseñar']]),
          o('B', t('Dedicated open-source quality framework', 'Framework de calidad dedicado de código abierto'), ['Add a framework for data quality checks and reports (e.g. Great Expectations, Soda, Deequ).', 'Añadir un framework de controles e informes de calidad (p. ej. Great Expectations, Soda, Deequ).'],
            [['Rich, reusable rule libraries', 'Reports that business users can read', 'Portable across engines'], ['Bibliotecas de reglas ricas y reutilizables', 'Informes que los usuarios de negocio pueden leer', 'Portable entre motores']],
            [['Another tool to integrate and maintain', 'Rules can be duplicated between tools', 'Needs a process to act on failures'], ['Otra herramienta que integrar y mantener', 'Las reglas pueden duplicarse entre herramientas', 'Hace falta un proceso para actuar ante fallos']]),
          o('C', t('Data observability product', 'Producto de observabilidad de datos'), ['Use a product that monitors freshness, volume and schema across tables and learns normal behaviour.', 'Usar un producto que monitorea frescura, volumen y esquema en las tablas y aprende el comportamiento normal.'],
            [['Broad coverage with little configuration', 'Anomaly detection and incident workflows', 'Lineage-based impact analysis'], ['Cobertura amplia con poca configuración', 'Detección de anomalías y flujos de incidentes', 'Análisis de impacto basado en linaje']],
            [['Licence cost', 'Alerts can be noisy until tuned', 'Does not replace explicit business rules'], ['Costo de licencia', 'Las alertas pueden ser ruidosas hasta ajustarlas', 'No reemplaza las reglas de negocio explícitas']])
        ]),

      d(['Consumption', 'Consumo'], ['How are data served and the semantic layer defined?', '¿Cómo se sirve el dato y se define la capa semántica?'],
        ['Consumers judge the platform by how fast and consistent their reports are. Ask the client: which BI tools are in use, how many users and how many run queries at the same time, which metrics must have a single definition, and whether apps or external parties also need access through APIs.',
          'Los consumidores juzgan la plataforma por la rapidez y consistencia de sus reportes. Preguntar al cliente: ¿qué herramientas de BI se usan?, ¿cuántos usuarios hay y cuántos consultan a la vez?, ¿qué métricas deben tener una única definición? y ¿también necesitan acceso aplicaciones o terceros mediante APIs?'],
        ['sqlwh', 'sem', 'bi'], [
          o('A', t('SQL endpoints of the lakehouse + BI-tool model', 'Endpoints SQL del lakehouse + modelo en la herramienta de BI'), ['Serve gold tables through the platform\'s SQL compute and define measures in the BI tool.', 'Servir las tablas oro con el cómputo SQL de la plataforma y definir las medidas en la herramienta de BI.'],
            [['Fewest components', 'Fast for BI teams to start', 'Uses the permissions of the platform'], ['Menos componentes', 'Rápido de arrancar para los equipos de BI', 'Aprovecha los permisos de la plataforma']],
            [['Metric definitions can diverge between tools', 'Switching BI tool means rebuilding models', 'Concurrency may need sizing and caching'], ['Las definiciones de métricas pueden divergir entre herramientas', 'Cambiar de herramienta de BI implica reconstruir los modelos', 'La concurrencia puede requerir dimensionamiento y caché']]),
          o('B', t('Semantic layer independent of the BI tool', 'Capa semántica independiente de la herramienta de BI'), ['Define metrics once in a dedicated semantic layer used by all tools and applications.', 'Definir las métricas una sola vez en una capa semántica dedicada que usan todas las herramientas y aplicaciones.'],
            [['One definition of each metric everywhere', 'Reduces lock-in to a BI tool', 'Can serve APIs and applications too'], ['Una única definición de cada métrica en todas partes', 'Reduce la dependencia de una herramienta de BI', 'También puede servir a APIs y aplicaciones']],
            [['Extra component to run and learn', 'Not every BI tool integrates equally well', 'Needs ownership of the metric catalogue'], ['Componente extra que operar y aprender', 'No todas las herramientas de BI se integran igual de bien', 'Requiere un responsable del catálogo de métricas']]),
          o('C', t('Dedicated serving store for specific use cases', 'Almacén de servicio dedicado para casos específicos'), ['Publish selected gold data to a separate store (MPP warehouse or low-latency analytical database) for demanding workloads.', 'Publicar datos oro seleccionados en un almacén aparte (almacén MPP o base analítica de baja latencia) para cargas exigentes.'],
            [['Predictable low latency under high concurrency', 'Isolates dashboards from heavy processing', 'Suitable for embedded analytics'], ['Baja latencia predecible con alta concurrencia', 'Aísla los tableros del procesamiento pesado', 'Adecuado para analítica embebida']],
            [['Another copy of the data to keep in sync', 'More cost and one more system to secure', 'Only justified by a measured need'], ['Otra copia del dato que mantener sincronizada', 'Más costo y un sistema más que asegurar', 'Solo se justifica con una necesidad medida']])
        ]),

      d(['Security', 'Seguridad'], ['What is the identity and access model?', '¿Cuál es el modelo de identidad y acceso?'],
        ['Access rules for sensitive data are hard to retrofit. Ask the client: which identity provider is the source of truth, which data is personal or regulated, who may see raw versus masked values, how joiners and leavers are handled, and how service accounts and pipelines authenticate.',
          'Las reglas de acceso a datos sensibles son difíciles de añadir después. Preguntar al cliente: ¿qué proveedor de identidad es la fuente de verdad?, ¿qué datos son personales o regulados?, ¿quién puede ver valores reales y quién enmascarados?, ¿cómo se gestionan altas y bajas de personas? y ¿cómo se autentican las cuentas de servicio y los pipelines?'],
        ['iam'], [
          o('A', t('RBAC with groups synced from the corporate IdP', 'RBAC con grupos sincronizados desde el IdP corporativo'), ['Grant access to roles that map to groups managed in the corporate identity provider.', 'Dar acceso a roles que corresponden a grupos gestionados en el proveedor de identidad corporativo.'],
            [['Simple to explain and audit', 'Joiners and leavers handled in one place', 'Works in every platform'], ['Simple de explicar y auditar', 'Altas y bajas gestionadas en un solo lugar', 'Funciona en todas las plataformas']],
            [['Number of roles can grow quickly', 'Coarse for column or row level needs', 'Needs naming and ownership rules for groups'], ['El número de roles puede crecer rápido', 'Es grueso para necesidades a nivel de columna o fila', 'Necesita reglas de nombres y responsables para los grupos']]),
          o('B', t('ABAC: tags and policies with masking and row filters', 'ABAC: etiquetas y políticas con enmascaramiento y filtros de fila'), ['Classify data with tags and let policies decide access, masking and row filtering, on top of RBAC.', 'Clasificar los datos con etiquetas y dejar que las políticas decidan acceso, enmascaramiento y filtrado de filas, sobre RBAC.'],
            [['Scales better as datasets grow', 'Protects personal data at column and row level', 'Policies follow the data'], ['Escala mejor al crecer los datasets', 'Protege el dato personal a nivel de columna y fila', 'Las políticas acompañan al dato']],
            [['Needs reliable classification first', 'More design effort upfront', 'Feature depth differs between platforms'], ['Requiere antes una clasificación fiable', 'Más esfuerzo de diseño al inicio', 'La profundidad de las funciones varía entre plataformas']]),
          o('C', t('External policy engine across tools', 'Motor de políticas externo para varias herramientas'), ['Use a separate product to define and enforce access policies across several engines.', 'Usar un producto aparte para definir y aplicar políticas de acceso en varios motores.'],
            [['One policy view across many engines', 'Useful in heterogeneous estates', 'Independent from any one vendor'], ['Una única vista de políticas sobre muchos motores', 'Útil en entornos heterogéneos', 'Independiente de un proveedor concreto']],
            [['Additional product, cost and integration', 'Enforcement depth depends on each connector', 'Another critical component to run'], ['Producto adicional, con costo e integración', 'La profundidad de la aplicación depende de cada conector', 'Otro componente crítico que operar']])
        ]),

      d(['Security', 'Seguridad'], ['What network and encryption posture?', '¿Qué postura de red y cifrado?'],
        ['Network and key decisions are costly to change after go-live. Ask the client: what the security team and regulators require, how on-premises systems will connect (VPN or dedicated links), whether public endpoints are allowed, who must hold the encryption keys, and how often keys rotate.',
          'Las decisiones de red y claves son costosas de cambiar después de salir a producción. Preguntar al cliente: ¿qué exigen el equipo de seguridad y los reguladores?, ¿cómo se conectarán los sistemas on-premise (VPN o enlaces dedicados)?, ¿se permiten endpoints públicos?, ¿quién debe custodiar las claves de cifrado? y ¿cada cuánto se rotan?'],
        ['kms', 'iam'], [
          o('A', t('Public endpoints with allow-lists, TLS and provider-managed keys', 'Endpoints públicos con listas de IP permitidas, TLS y claves del proveedor'), ['Keep services reachable over the internet but restricted by IP, strong authentication and encryption.', 'Mantener los servicios accesibles por internet pero restringidos por IP, autenticación fuerte y cifrado.'],
            [['Fastest to set up and cheapest to run', 'Less network design needed', 'Fine for early phases or low-sensitivity data'], ['Lo más rápido de configurar y más barato de operar', 'Requiere menos diseño de red', 'Adecuado para fases iniciales o datos poco sensibles']],
            [['Larger attack surface', 'Often not acceptable for regulated data', 'IP lists are hard to maintain for remote users'], ['Mayor superficie de ataque', 'Muchas veces no es aceptable para datos regulados', 'Las listas de IP son difíciles de mantener con usuarios remotos']]),
          o('B', t('Private connectivity, no public access', 'Conectividad privada, sin acceso público'), ['Reach services only through private endpoints and private links, with on-premises over VPN or dedicated lines.', 'Acceder a los servicios solo por endpoints y enlaces privados, con on-premise por VPN o líneas dedicadas.'],
            [['Much smaller attack surface', 'Meets most security and regulatory expectations', 'Traffic stays off the public internet'], ['Superficie de ataque mucho menor', 'Cumple la mayoría de las expectativas de seguridad y regulación', 'El tráfico no pasa por internet público']],
            [['More design, DNS and routing work', 'Harder for users and tools outside the network', 'Private networking features add cost'], ['Más trabajo de diseño, DNS y enrutamiento', 'Más difícil para usuarios y herramientas fuera de la red', 'Las funciones de red privada añaden costo']]),
          o('C', t('Private connectivity and customer-managed keys', 'Conectividad privada y claves gestionadas por el cliente'), ['As B, plus encryption keys that the client creates, controls and can revoke.', 'Como B, más claves de cifrado que el cliente crea, controla y puede revocar.'],
            [['Client controls key lifecycle and revocation', 'Clear separation of duties for key custodians', 'Often requested by regulators'], ['El cliente controla el ciclo de vida de las claves y su revocación', 'Separación clara de funciones entre custodios de claves', 'Suele ser solicitado por los reguladores']],
            [['Key management becomes a critical process', 'Losing or disabling a key can block access to data', 'Some services support it only partially'], ['La gestión de claves se vuelve un proceso crítico', 'Perder o desactivar una clave puede bloquear el acceso a los datos', 'Algunos servicios lo soportan solo en parte']])
        ]),

      d(['Operations', 'Operaciones'], ['How are environments, infrastructure as code and CI/CD set up?', '¿Cómo se organizan los ambientes, la infraestructura como código y el CI/CD?'],
        ['A repeatable way to build environments and release changes avoids manual drift and speeds up onboarding. Ask the client: how many environments (dev, test, prod) and how they are isolated, what data is allowed outside production, the approval process for releases, and which tools the company already uses for pipelines and code hosting.',
          'Una forma repetible de crear ambientes y publicar cambios evita la deriva manual y acelera la incorporación de personas. Preguntar al cliente: ¿cuántos ambientes (dev, test, prod) y cómo se aíslan?, ¿qué datos se permiten fuera de producción?, ¿cuál es el proceso de aprobación de despliegues? y ¿qué herramientas usa ya la empresa para pipelines y alojamiento de código?'],
        ['cicd'], [
          o('A', t('Terraform / OpenTofu with Git-based CI/CD', 'Terraform / OpenTofu con CI/CD basado en Git'), ['Define cloud and platform resources in code, reviewed in pull requests and deployed by pipelines, one environment per account or workspace.', 'Definir recursos de la nube y la plataforma como código, revisados en pull requests y desplegados por pipelines, con un ambiente por cuenta o workspace.'],
            [['Same approach across clouds and many platforms', 'Reviewable, repeatable and auditable', 'Large community and module ecosystem'], ['Mismo enfoque entre nubes y muchas plataformas', 'Revisable, repetible y auditable', 'Comunidad grande y ecosistema de módulos']],
            [['State management needs care', 'Requires discipline in code review', 'Provider updates can lag new features'], ['La gestión del estado requiere cuidado', 'Exige disciplina en la revisión de código', 'Los proveedores pueden tardar en soportar funciones nuevas']]),
          o('B', t('Cloud-native IaC (CloudFormation, Bicep, …)', 'IaC nativo de la nube (CloudFormation, Bicep, …)'), ['Use the infrastructure-as-code language of the chosen cloud.', 'Usar el lenguaje de infraestructura como código de la nube elegida.'],
            [['First-class support for the cloud\'s services', 'No external state to manage', 'Integrated with the cloud\'s deployment tooling'], ['Soporte de primera para los servicios de esa nube', 'No hay estado externo que gestionar', 'Integrado con las herramientas de despliegue de la nube']],
            [['Tied to one cloud', 'Does not cover the lakehouse platform as well', 'Skills not reusable elsewhere'], ['Atado a una sola nube', 'No cubre tan bien la plataforma lakehouse', 'Las habilidades no se reutilizan en otros contextos']]),
          o('C', t('Platform-native deployment tooling', 'Herramientas de despliegue nativas de la plataforma'), ['Use the platform\'s own packaging and promotion features for data assets, with minimal infrastructure code.', 'Usar las funciones propias de la plataforma para empaquetar y promover activos de datos, con poco código de infraestructura.'],
            [['Quick to adopt for data teams', 'Understands platform objects natively', 'Less to learn at first'], ['Rápido de adoptar para los equipos de datos', 'Entiende los objetos de la plataforma de forma nativa', 'Menos que aprender al principio']],
            [['Covers only what the platform exposes', 'Cloud resources still need their own IaC', 'Not portable if the platform changes'], ['Cubre solo lo que expone la plataforma', 'Los recursos de la nube siguen necesitando su propio IaC', 'No es portable si cambia la plataforma']])
        ]),

      d(['Operations', 'Operaciones'], ['What is the operating model?', '¿Cuál es el modelo operativo?'],
        ['Technology succeeds or fails on who owns the data and who supports it. Ask the client: how large and how skilled the central data team is, whether business domains have engineers, who is accountable for data quality, how new requests are prioritised, and how much autonomy the domains want.',
          'La tecnología triunfa o fracasa según quién es dueño del dato y quién da soporte. Preguntar al cliente: ¿qué tan grande y cualificado es el equipo central de datos?, ¿los dominios de negocio tienen ingenieros?, ¿quién responde por la calidad de los datos?, ¿cómo se priorizan las nuevas solicitudes? y ¿cuánta autonomía quieren los dominios?'],
        ['transf', 'catalog'], [
          o('A', t('Central data team', 'Equipo central de datos'), ['One team builds and runs the platform and the data products.', 'Un solo equipo construye y opera la plataforma y los productos de datos.'],
            [['Consistent standards and fast start', 'Concentrated skills and clear responsibility', 'Simple governance'], ['Estándares coherentes y arranque rápido', 'Habilidades concentradas y responsabilidad clara', 'Gobierno simple']],
            [['Becomes a bottleneck as demand grows', 'Distance from business context', 'Backlog and prioritisation conflicts'], ['Se convierte en cuello de botella al crecer la demanda', 'Distancia respecto al contexto de negocio', 'Conflictos de prioridades y cola de pendientes']]),
          o('B', t('Hub and spoke', 'Hub and spoke (centro y satélites)'), ['A central platform team provides the platform and standards; engineers embedded in business areas build the data products.', 'Un equipo central de plataforma ofrece la plataforma y los estándares; ingenieros integrados en las áreas de negocio construyen los productos de datos.'],
            [['Balance between consistency and proximity to the business', 'Scales better than a fully central team', 'Easier step from a central start'], ['Equilibrio entre coherencia y cercanía al negocio', 'Escala mejor que un equipo totalmente central', 'Transición más fácil desde un inicio centralizado']],
            [['Needs clear roles between hub and spokes', 'Risk of divergent practices without a guild or standards', 'Spoke teams must be staffed'], ['Requiere roles claros entre el centro y los satélites', 'Riesgo de prácticas divergentes sin comunidad ni estándares', 'Los equipos satélite hay que dotarlos de personas']]),
          o('C', t('Data mesh (domain-owned data products)', 'Data mesh (productos de datos propiedad de los dominios)'), ['Domains own and publish their data products, supported by a self-service platform and federated governance.', 'Los dominios son dueños de sus productos de datos y los publican, apoyados en una plataforma de autoservicio y un gobierno federado.'],
            [['Ownership sits with those who know the data', 'Scales with the organisation', 'Faster delivery in mature domains'], ['La propiedad está en quienes conocen el dato', 'Escala con la organización', 'Entrega más rápida en dominios maduros']],
            [['Demands organisational maturity and investment', 'Needs a strong self-service platform first', 'Hard to start in a greenfield with few skills'], ['Exige madurez organizacional e inversión', 'Necesita antes una plataforma de autoservicio sólida', 'Difícil de iniciar en un greenfield con pocas habilidades']])
        ]),

      d(['Operations', 'Operaciones'], ['How is cost managed (FinOps)?', '¿Cómo se gestionan los costos (FinOps)?'],
        ['Consumption-based platforms make cost a design topic from day one. These approaches can be combined; the question is where to start. Ask the client: who pays for the platform, whether costs must be charged back to business units, what the monthly budget is, who receives alerts, and whether committed-spend discounts are possible.',
          'Las plataformas de pago por consumo hacen del costo un tema de diseño desde el primer día. Estos enfoques se pueden combinar; la pregunta es por dónde empezar. Preguntar al cliente: ¿quién paga la plataforma?, ¿hay que repartir los costos entre unidades de negocio?, ¿cuál es el presupuesto mensual?, ¿quién recibe las alertas? y ¿es posible un compromiso de gasto con descuentos?'],
        ['obs'], [
          o('A', t('Tags, budgets and a monthly review', 'Etiquetas, presupuestos y revisión mensual'), ['Tag every resource, set budget alerts and review costs monthly in the platform team.', 'Etiquetar cada recurso, fijar alertas de presupuesto y revisar los costos cada mes en el equipo de plataforma.'],
            [['Light to start and visible quickly', 'Catches surprises early', 'Builds the habit of cost awareness'], ['Ligero de iniciar y da visibilidad rápida', 'Detecta sorpresas pronto', 'Crea el hábito de la conciencia de costos']],
            [['Mostly reactive', 'Depends on consistent tagging', 'Does not by itself reduce cost'], ['Principalmente reactivo', 'Depende de un etiquetado consistente', 'Por sí solo no reduce el costo']]),
          o('B', t('Showback / chargeback with quotas and guardrails', 'Showback / chargeback con cuotas y límites'), ['Allocate costs to teams or domains, set quotas and automatic shutdown policies.', 'Asignar los costos a equipos o dominios, y fijar cuotas y políticas de apagado automático.'],
            [['Teams see and own what they spend', 'Prevents runaway jobs and idle compute', 'Supports business cases per domain'], ['Los equipos ven y se hacen cargo de lo que gastan', 'Evita jobs descontrolados y cómputo ocioso', 'Respalda casos de negocio por dominio']],
            [['Needs a stable allocation model and agreement with finance', 'Shared costs are hard to split fairly', 'More governance effort'], ['Requiere un modelo de asignación estable y acuerdo con finanzas', 'Los costos compartidos son difíciles de repartir con justicia', 'Más esfuerzo de gobierno']]),
          o('C', t('Commitments and capacity optimisation', 'Compromisos y optimización de capacidad'), ['After a baseline period, buy committed capacity or discounts and right-size workloads.', 'Tras un periodo de línea base, contratar capacidad comprometida o descuentos y ajustar el tamaño de las cargas.'],
            [['Lower unit cost for steady workloads', 'Based on real usage data', 'Gives a more predictable budget'], ['Menor costo unitario para cargas estables', 'Basado en datos reales de uso', 'Da un presupuesto más predecible']],
            [['Too early in a greenfield: usage is not known yet', 'Commitments reduce flexibility', 'Needs continuous review to avoid unused capacity'], ['Demasiado pronto en un greenfield: aún no se conoce el uso', 'Los compromisos reducen la flexibilidad', 'Requiere revisión continua para no dejar capacidad sin usar']])
        ])
    ]
  }];
})();
